Repository Trustmarque/cloudmarque-azure-pwsh, pull requests merged in 2020-09, with the labels that each got.

#72 Iaas - networking update resource group deployment re-design
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.json
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
  Cloudmarque.Azure/Resources/Project/networking/csv/resourceGroup.csv
  Cloudmarque.Azure/Resources/Project/networking/csv/vnet.csv
  Cloudmarque.Azure/Resources/Project/networking/yml/customfolder/nsg-3.yml
  Cloudmarque.Azure/Resources/Project/networking/yml/customfolder/nsg-4.yml
  Cloudmarque.Azure/Resources/Project/networking/yml/networkSecurityGroups/nsg-1.yml
  Cloudmarque.Azure/Resources/Project/networking/yml/networkSecurityGroups/nsg-2.yml
  Cloudmarque.Azure/Resources/Project/networking/yml/networking.yml
  Cloudmarque.Azure/Resources/Project/networking/yml/routeTables/udr-1.yml
  Cloudmarque.Azure/Resources/Project/networking/yml/routeTables/udr-2.yml
Labels: bug

#76 Iaas - networking - add location defaults
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
Labels: bug

#39 Iaas wvd initial implementation
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzIaaSWVD.ps1
  Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDEnvironment.json
  Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDHosts.json
  Cloudmarque.Azure/Public/IaaS/wvd/New-CmAzWVDPostSetup.json
  Cloudmarque.Azure/Resources/Project/_names/resources.yml
  Cloudmarque.Azure/Resources/Project/wvd.yml
Labels: Initial

#79 Remove release check from Cloudmarque docs
  azure-pipelines.yml
Labels: bug

#78 #77 - Billing Rule Validation Fix
  Cloudmarque.Azure/Public/Core/budgets/New-CmAzCoreBillingRule.ps1
Labels: bug

#82 Update dependencies, remove scriptstoprocess entry
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  Cloudmarque.Azure/Install-Dependencies.ps1
Labels: enhancement

#86 Add missing component documentation, adjust spacing in core cmdlet
  Cloudmarque.Azure/Public/Common/Clear-CmAzContext.ps1
  Cloudmarque.Azure/Public/Common/Get-CmAzContext.ps1
  Cloudmarque.Azure/Public/Common/Get-CmAzResourceName.ps1
  Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
  Cloudmarque.Azure/Public/Core/keyvault/New-CmAzCoreKeyVault.ps1
Labels: documentation

#81 Paas - New-CmAzPaasSharedImageGallery initial draft
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.json
  Cloudmarque.Azure/Public/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.ps1
  Cloudmarque.Azure/Resources/Project/automation.yml
  Cloudmarque.Azure/Resources/Project/sharedImageGallery.yml
Labels: enhancement

#88 revert automation file setting changes
  Cloudmarque.Azure/Resources/Project/automation.yml
Labels: bug

#89 re-add missing dependency
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  azure-pipelines.yml
Labels: bug
