Repository Trustmarque/cloudmarque-azure-pwsh, pull requests merged in 2020-08, with the labels that each got.

#49 Add extra properties to global context
  Cloudmarque.Azure/Public/Common/Clear-CmAzContext.ps1
  Cloudmarque.Azure/Public/Common/Get-CmAzContext.ps1
  Cloudmarque.Azure/Public/Common/Get-CmAzService.ps1
  Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
  Tests/Test-CmAzContext.Tests.ps1
Labels: enhancement

#48 Paas sql initial implementation
  .gitignore
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  Cloudmarque.Azure/Public/PaaS/sql/2_SQL.json
  Cloudmarque.Azure/Public/PaaS/sql/New-CmAzPaasSql.json
  Cloudmarque.Azure/Public/PaaS/sql/New-CmAzPaasSql.ps1
  Cloudmarque.Azure/Resources/Project/automation.yml
  Cloudmarque.Azure/Resources/Project/bastionHost.yml
  Cloudmarque.Azure/Resources/Project/sql.yml
Labels: Initial

#24 Runbook: auto delete resources on date set in cm-delete tag
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  Cloudmarque.Azure/Cloudmarque.Azure.psm1
  Cloudmarque.Azure/Private/Runbooks/Delete-TaggedResource.Runbook.ps1
  Cloudmarque.Azure/Public/Core/automation/DeleteTaggedResource/Set-CmAzCoreAutomationDeleteResource.json
  Cloudmarque.Azure/Public/Core/automation/DeleteTaggedResource/Set-CmAzCoreAutomationDeleteResource.ps1
  Cloudmarque.Azure/Public/Core/automation/New-CmAzCoreAutomation.json
  Cloudmarque.Azure/Public/Core/automation/New-CmAzCoreAutomation.ps1
  Cloudmarque.Azure/Resources/Project/automation.yml
  Cloudmarque.Azure/Resources/Project/deleteservice.yml
  Install-Dependencies.ps1
  Tests/Get-CmAzResourceName.Tests.ps1
  Tests/Test-CmAzContext.Tests.ps1
  Tests/Test-CodeQuality.Tests.ps1
Labels: enhancement

#57 Pipelines Create PSGallery and GitHub release
  Build-CloudmarqueAzure.ps1
  Cloudmarque.Azure/Cloudmarque.Azure.nuspec
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  Cloudmarque.Azure/Cloudmarque.Azure.psm1
  Cloudmarque.Azure/Install-Dependencies.ps1
  Cloudmarque.Azure/Private/Runbooks/Delete-TaggedResource.Runbook.ps1
  Cloudmarque.Azure/Public/Common/Get-CmAzContext.ps1
  Cloudmarque.Azure/Public/Common/Get-CmAzResourceName.ps1
  Cloudmarque.Azure/Public/Common/Get-CmAzService.ps1
  Cloudmarque.Azure/Public/Common/Get-CmAzSettingsFile.ps1
  Cloudmarque.Azure/Public/Common/New-CmAzProject.ps1
  Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
  Cloudmarque.Azure/Public/Common/Test-CmAzPackage.ps1
  Install-Dependencies.ps1
  New-CloudmarqueAzureDocs.ps1
  Sync-CloudmarqueAzure.ps1
  Test-CloudmarqueAzure.ps1
  azure-pipelines.yml
Labels: enhancement

#59 Point condition at master
  azure-pipelines.yml
Labels: bug

#70 Iaas - networking- fixing issue with missing if
  .gitignore
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
Labels: bug
