Repository Trustmarque/cloudmarque-azure-pwsh, pull requests merged in 2020-12, with the labels that each got.

#153 delete existing jobschedules
  Cloudmarque.Azure/Public/IaaS/vm/Set-CmAzIaasUpdateManagement.ps1
Labels: bug

#155 Update tagging cmdlet name/validate resource ids
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  Cloudmarque.Azure/Private/Tagging/Set-DeployedResourceTags.ps1
  Cloudmarque.Azure/Public/Common/Set-CmAzTag.ps1
Labels: consistency

#156 Custom DNS implementation #120
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.json
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
  Cloudmarque.Azure/Resources/Project/networking/csv/vnet.csv
  Cloudmarque.Azure/Resources/Project/networking/yml/vnets/vnet-1.yml
Labels: enhancement

#154 Integration Pipeline Amends and Testing
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  Cloudmarque.Azure/Public/IaaS/vm/Set-CmAzIaasUpdateManagement.json
  Cloudmarque.Azure/Public/IaaS/vm/Set-CmAzIaasUpdateManagement.ps1
  Cloudmarque.Azure/Public/Security/security-centre/Set-CmAzSecurityCentre.json
  Cloudmarque.Azure/Public/Security/security-centre/Set-CmAzSecurityCentre.ps1
  Cloudmarque.Azure/Resources/Project/_tags/globalTags.yml
  Cloudmarque.Azure/Resources/Project/updateManagement.yml
  Cloudmarque.Azure/Resources/Project/vpngw.yml
  azure-integration-pipelines.yml
Labels: enhancement

#166 New-CmAzIaasNetworking - Add NSG DiagnosticSettings and FlowLogs
  Cloudmarque.Azure/Public/Common/Set-CmAzTag.ps1
  Cloudmarque.Azure/Public/Core/automation/New-CmAzCoreAutomation.ps1
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.Nsgs.json
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ResourceGroups.json
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.json
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
  Cloudmarque.Azure/Public/IaaS/storage/New-CmAzIaasStorage.json
  Cloudmarque.Azure/Resources/Project/monitor.yml
  Cloudmarque.Azure/Resources/Project/networking/csv/nsg.csv
  Cloudmarque.Azure/Resources/Project/networking/csv/vnet.csv
  Cloudmarque.Azure/Resources/Project/networking/yml/networkSecurityGroups/nsg-1.yml
  Cloudmarque.Azure/Resources/Project/networking/yml/networkSecurityGroups/nsg-2.yml
  Cloudmarque.Azure/Resources/Project/networking/yml/networking.yml
  Cloudmarque.Azure/Resources/Project/run.ps1
  Cloudmarque.Azure/Resources/Project/storage.yml
  azure-integration-pipelines.yml
Labels: enhancement

#167 General - relative path handling
  Cloudmarque.Azure/Public/Common/Get-CmAzSettingsFile.ps1
  Cloudmarque.Azure/Public/Common/New-CmAzProject.ps1
  Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
  Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
  Cloudmarque.Azure/Public/Core/automation/Set-CmAzCoreAutomationDeleteResource.ps1
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
  Cloudmarque.Azure/Resources/Project/networking/yml/networking.yml
  Test-CloudmarqueAzure.ps1
  Tests/Test-CmAzContext.Tests.ps1
Labels: consistency
