Repository Trustmarque/cloudmarque-azure-pwsh, pull requests merged in 2020-11, with the labels that each got.

#92 87 - Consistent Documentation
  Cloudmarque.Azure/Public/Common/Get-CmAzResourceName.ps1
  Cloudmarque.Azure/Public/Common/Get-CmAzService.ps1
  Cloudmarque.Azure/Public/Common/Get-CmAzSettingsFile.ps1
  Cloudmarque.Azure/Public/Common/Get-CmAzSubscriptionName.ps1
  Cloudmarque.Azure/Public/Common/New-CmAzProject.ps1
  Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
  Cloudmarque.Azure/Public/IaaS/bastionhost/New-CmAzIaasBastionHost.ps1
  Cloudmarque.Azure/Public/IaaS/recoveryvault/New-CmAzIaasRecoveryServicesVault.ps1
  Cloudmarque.Azure/Public/IaaS/storage/New-CmAzIaasStorage.ps1
  Cloudmarque.Azure/Public/IaaS/vm/New-CmAzIaasVm.ps1
  Cloudmarque.Azure/Public/IaaS/vpngw/New-CmAzIaasVpnGw.ps1
  Cloudmarque.Azure/Public/PaaS/sql/New-CmAzPaasSql.ps1
  Cloudmarque.Azure/Public/PaaS/web-static/New-CmAzPaasWebStatic.ps1
  Cloudmarque.Azure/Public/PaaS/web/New-CmAzPaasWeb.ps1
  Tests/Test-Documentation.Tests.ps1
Labels: documentation, enhancement

#119 Remove new-cmazpaasstaticweb output
  Cloudmarque.Azure/Public/PaaS/web-static/New-CmAzPaasWebStatic.ps1
Labels: bug

#122 Web stack refactoring.
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  Cloudmarque.Azure/Public/PaaS/web/New-CmAzPaasWeb-ApiManagementServices.json
  Cloudmarque.Azure/Public/PaaS/web/New-CmAzPaasWeb-Frontdoor.json
  Cloudmarque.Azure/Public/PaaS/web/New-CmAzPaasWeb-Webapp.json
  Cloudmarque.Azure/Public/PaaS/web/New-CmAzPaasWeb.json
  Cloudmarque.Azure/Public/PaaS/web/New-CmAzPaasWeb.ps1
  Cloudmarque.Azure/Resources/Project/web.yml
Labels: enhancement

#130 Resolves issue with replication - #129
  Cloudmarque.Azure/Public/IaaS/storage/New-CmAzIaasStorage.ps1
  Cloudmarque.Azure/Resources/Project/sql.yml
Labels: bug

#136 New-CmAzPaasWeb - Update to cdn profile
  Cloudmarque.Azure/Public/PaaS/web/New-CmAzPaasWeb-Webapp.json
  Cloudmarque.Azure/Public/PaaS/web/New-CmAzPaasWeb.ps1
  Cloudmarque.Azure/Resources/Project/web.yml
Labels: bug
