Repository Trustmarque/cloudmarque-azure-pwsh, pull requests merged in 2021-02, with the labels that each got.

#222 Add conditional hotfix version
  azure-pipelines.yml
Labels: enhancement

#223 Update azure-pipelines.yml
  azure-pipelines.yml
Labels: bug

#225 New-CmAzPaasFunction : Initial Implementation
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  Cloudmarque.Azure/Public/Deploy/New-CmAzDeployment.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction.AppServicePlan.json
  Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction.Consumption.json
  Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/web/New-CmAzPaasWeb.ps1
  Cloudmarque.Azure/Resources/Project/functions.yml
  Cloudmarque.Azure/Resources/Project/web.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzPaasWeb.Schema.json
Labels: enhancement

#228 Action Groups - Change naming convention
  Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
Labels: consistency

#227 Auto-Accept Marketplace terms
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.ps1
  Cloudmarque.Azure/Resources/Project/networking/csv/vnet.csv
  Cloudmarque.Azure/Resources/Project/virtualmachines.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVm.Schema.json
Labels: enhancement

#229 General update deployment names
  Cloudmarque.Azure/Public/Common/Get-CmAzResourceName.ps1
  Cloudmarque.Azure/Public/Deploy/Core/automation/New-CmAzCoreAutomation.ps1
  Cloudmarque.Azure/Public/Deploy/Core/budgets/New-CmAzCoreBillingRule.ps1
  Cloudmarque.Azure/Public/Deploy/Core/keyvault/New-CmAzCoreKeyVault.ps1
  Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/bastionhost/New-CmAzIaasBastionHost.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/New-CmAzIaasNetworking.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/recoveryvault/New-CmAzIaasRecoveryServicesVault.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/storage/New-CmAzIaasStorage.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/Set-CmAzIaasUpdateManagement.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/vpngw/New-CmAzIaasVpnGw.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/wvd/New-CmAzIaaSWVD.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/sql/New-CmAzPaasSql.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/web-static/New-CmAzPaasWebStatic.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/web/New-CmAzPaasWeb.ps1
  Cloudmarque.Azure/Public/Deploy/Security/security-centre/Set-CmAzSecurityCentre.ps1
  Cloudmarque.Azure/Resources/Project/_names/generators.yml
  Cloudmarque.Azure/Resources/Project/_names/resources.yml
Labels: consistency

#231 Iaas - VM deployment improvements
  Cloudmarque.Azure/Private/Tagging/Set-DeployedResourceTags.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/New-CmAzIaasNetworking.Nsgs.json
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/New-CmAzIaasNetworking.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.json
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.ps1
  Cloudmarque.Azure/Resources/Project/_names/generators.yml
  Cloudmarque.Azure/Resources/Project/_names/regions.yml
  Cloudmarque.Azure/Resources/Project/_names/resources.yml
  Cloudmarque.Azure/Resources/Project/networking/csv/vnet.csv
  Cloudmarque.Azure/Resources/Project/virtualmachines.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVm.Schema.json
  azure-integration-pipelines.yml
Labels: enhancement

#236 Json schema validation fixes
  Cloudmarque.Azure/Private/Utility/New-Secret.ps1
  Cloudmarque.Azure/Resources/Project/_names/regions.yml
  Cloudmarque.Azure/Resources/Project/networking/csv/vnet.csv
  Cloudmarque.Azure/Resources/Schema/New-CmAzCoreBillingRule.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzCoreKeyVault.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzCoreMonitor.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasBastionHost.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasRecoveryServicesPolicy.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasRecoveryServicesVault.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasStorage.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVm.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVpnGw.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasWvd.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzPaasSharedImageGallery.Schema.Json
  Cloudmarque.Azure/Resources/Schema/New-CmAzPaasSql.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzPaasWeb.Schema.json
  Cloudmarque.Azure/Resources/Schema/Set-CmAzCoreAutomationDeleteResource.Schema.json
  Cloudmarque.Azure/Resources/Schema/Set-CmAzIaasUpdateManagement.Schema.json
  azure-integration-pipelines.yml
Labels: bug

#237 initial implementation
  Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.json
  Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
  Cloudmarque.Azure/Resources/Project/monitor.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzCoreMonitor.Schema.json
Labels: enhancement
