Repository Trustmarque/cloudmarque-azure-pwsh, pull requests merged in 2021-01, with the labels that each got.

#168 Iaas - Network script to support vnet peering
  Cloudmarque.Azure/Public/Common/Set-CmAzContext.ps1
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.vnetPeerings.json
  Cloudmarque.Azure/Resources/Project/networking/csv/vnet.csv
  Cloudmarque.Azure/Resources/Project/networking/yml/networking.yml
  Cloudmarque.Azure/Resources/Project/networking/yml/vnets/vnet-1.yml
  azure-integration-pipelines.yml
Labels: enhancement

#172 Enable parallel deployment of unique resources
  Cloudmarque.Azure/Public/PaaS/sql/New-CmAzPaasSql.ps1
  Cloudmarque.Azure/Resources/Project/keyvaults.yml
  Cloudmarque.Azure/Resources/Project/sql.yml
  azure-integration-pipelines.yml
Labels: enhancement

#176 New-CmAzIaasVm - support for marketplace images
  Cloudmarque.Azure/Public/IaaS/vm/New-CmAzIaasVm.json
  Cloudmarque.Azure/Public/IaaS/vm/New-CmAzIaasVm.ps1
  Cloudmarque.Azure/Resources/Project/virtualmachines.yml
Labels: enhancement

#179 New-CmAzIaasNetworking - allow route propagation
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.json
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
  Cloudmarque.Azure/Resources/Project/networking/csv/udr.csv
Labels: enhancement

#181 Centralise baseline alert configuration for core
  Cloudmarque.Azure/Public/Core/New-CmAzCore.ps1
  Cloudmarque.Azure/Public/Core/automation/New-CmAzCoreAutomation.ps1
  Cloudmarque.Azure/Public/Core/keyvault/New-CmAzCoreKeyVault.json
  Cloudmarque.Azure/Public/Core/keyvault/New-CmAzCoreKeyVault.ps1
  Cloudmarque.Azure/Public/Core/monitoring/New-CmAzCoreMonitor.Monitoring.json
  Cloudmarque.Azure/Public/Core/monitoring/New-CmAzCoreMonitor.json
  Cloudmarque.Azure/Public/Core/monitoring/New-CmAzCoreMonitor.ps1
  Cloudmarque.Azure/Public/IaaS/networking/New-CmAzIaasNetworking.ps1
  Cloudmarque.Azure/Resources/Project/_names/resources.yml
  Cloudmarque.Azure/Resources/Project/keyvaults.yml
  Cloudmarque.Azure/Resources/Project/monitor.yml
  Cloudmarque.Azure/Resources/Project/virtualmachines.yml
  Tests/Get-CmAzResourceName.Tests.ps1
Labels: consistency, enhancement

#185 Comment custom marketplace settings
  Cloudmarque.Azure/Resources/Project/keyvaults.yml
  Cloudmarque.Azure/Resources/Project/virtualmachines.yml
  azure-integration-pipelines.yml
Labels: bug

#208 New cmaziaasnetworking 1.0.8.1 hotfixes
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/New-CmAzIaasNetworking.Nsgs.json
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/New-CmAzIaasNetworking.ps1
  azure-pipelines.yml
Labels: bug
