Repository Trustmarque/cloudmarque-azure-pwsh, pull requests merged in 2021-03, with the labels that each got.

#238 Resolves Availability Set issues
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.json
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.ps1
  Cloudmarque.Azure/Resources/Project/monitor.yml
  Cloudmarque.Azure/Resources/Project/virtualmachines.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVm.Schema.json
Labels: bug

#239 New README
  README.md
Labels: documentation

#241 Set checked branch back to master
  azure-pipelines.yml
Labels: bug

#242 Fix artifact creation
  azure-pipelines.yml
Labels: bug

#243 New-CmAzCoreMonitor - Action group name hotfix
  Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
Labels: bug

#244 fixes to abs and pgs
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.json
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.ps1
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVm.Schema.json
Labels: bug

#245 Release 1.0.10.1
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
Labels: planned

#246 update module version
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
Labels: planned

#247 Fix release step in azure pipeline
  azure-pipelines.yml
Labels: bug

#249 TimeZone support for windows VM
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.json
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/timeZones.yml
  Cloudmarque.Azure/Resources/Project/virtualmachines.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVm.Schema.json
Labels: enhancement

#253 multi project config fix
  Tests/Schema-Validation.Tests.ps1
Labels: bug

#250 Iaas - add anitmalware extension
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.ResourceGroups.json
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.json
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/localConfigs.yml
  Cloudmarque.Azure/Resources/Project/Integration/virtualmachines.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasVm.Schema.json
Labels: enhancement
