Repository Trustmarque/cloudmarque-azure-pwsh, pull requests merged in 2021-08, with the labels that each got.

#342 Core add new cm az custom extension
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  Cloudmarque.Azure/Private/Utility/Resolve-FilePath.ps1
  Cloudmarque.Azure/Public/Deploy/Core/extension/New-CmAzCustomExtension.ps1
  Cloudmarque.Azure/Public/New-CmAzDeployment.ps1
  Cloudmarque.Azure/Resources/Project/Integration/_extensions/extension.yml
  Cloudmarque.Azure/Resources/Project/Integration/_extensions/template.json
  Cloudmarque.Azure/Resources/Project/Integration/keyvaults.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzCustomExtension.Schema.json
  azure-integration-pipelines.yml
Labels: enhancement

#343 Allow passing in of monitor resources
  Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.json
  Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
  Cloudmarque.Azure/Resources/Project/Integration/monitor.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzCoreMonitor.Schema.json
Labels: enhancement

#345 updated function syntax
  Cloudmarque.Azure/Private/Tagging/Set-DeployedResourceTags.ps1
  Cloudmarque.Azure/Private/Tagging/Set-GlobalServiceValues.ps1
  Cloudmarque.Azure/Private/Utility/ConvertTo-HashTable.ps1
  Cloudmarque.Azure/Private/Utility/Get-Settings.ps1
  Cloudmarque.Azure/Private/Utility/Merge-Hashtables.ps1
  Cloudmarque.Azure/Private/Utility/New-Secret.ps1
  Cloudmarque.Azure/Private/Utility/Resolve-FilePath.ps1
  Cloudmarque.Azure/Private/Utility/Write-CommandStatus.ps1
Labels: consistency

#346 General consistent subtemplate names
  Cloudmarque.Azure/Public/Deploy/Core/keyvault/New-CmAzCoreKeyVault.json
  Cloudmarque.Azure/Public/Deploy/Core/keyvault/New-CmAzCoreKeyVault.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/bastionhost/New-CmAzIaasBastionHost.json
  Cloudmarque.Azure/Public/Deploy/IaaS/bastionhost/New-CmAzIaasBastionHost.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewallPolicies.json
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.json
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/firewall/New-CmAzIaasFirewalls.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/privateEndpoints/New-CmAzIaasPrivateEndpoints.json
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/privateEndpoints/New-CmAzIaasPrivateEndpoints.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/storage/New-CmAzIaasStorage.json
  Cloudmarque.Azure/Public/Deploy/IaaS/storage/New-CmAzIaasStorage.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.json
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/vpngw/New-CmAzIaasVpnGw.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/wvd/New-CmAzIaasWvd.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/wvd/New-CmAzWVDEnvironment.json
  Cloudmarque.Azure/Public/Deploy/IaaS/wvd/New-CmAzWVDPostSetup.json
  Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction.AppServicePlan.json
  Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction.Consumption.json
  Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.json
  Cloudmarque.Azure/Public/Deploy/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/sql/New-CmAzPaasSql.json
  Cloudmarque.Azure/Public/Deploy/PaaS/sql/New-CmAzPaasSql.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/web/New-CmAzPaasWeb-ApiManagementServices.json
  Cloudmarque.Azure/Public/Deploy/PaaS/web/New-CmAzPaasWeb-Webapp.json
  Cloudmarque.Azure/Public/Deploy/PaaS/web/New-CmAzPaasWeb.ps1
Labels: bug

#348 Security - New-CmAzSecurityPolicy initial implementation
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
  Cloudmarque.Azure/Public/Common/Get-CmAzSettingsFile.ps1
  Cloudmarque.Azure/Public/Deploy/Security/security-policy/New-CmAzSecurityPolicy.ps1
  Cloudmarque.Azure/Public/New-CmAzDeployment.ps1
  Cloudmarque.Azure/Resources/Project/Integration/_policies/allowed-locations.json
  Cloudmarque.Azure/Resources/Project/Integration/_policies/allowed-locations.params.json
  Cloudmarque.Azure/Resources/Project/Integration/securityPolicies.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzSecurityPolicy.Schema.json
Labels: enhancement, investigation
