Repository Trustmarque/cloudmarque-azure-pwsh, pull requests merged in 2021-06, with the labels that each got.

#296 Log Alert Suppression and Alert Naming
  Cloudmarque.Azure/Public/Deploy/Monitor/logAlerts/New-CmAzMonitorLogAlerts.json
  Cloudmarque.Azure/Public/Deploy/Monitor/logAlerts/New-CmAzMonitorLogAlerts.ps1
  Cloudmarque.Azure/Public/Deploy/Monitor/logAlerts/standardDefinitions.yml
  Cloudmarque.Azure/Public/Deploy/Monitor/metricAlerts/New-CmAzMonitorMetricAlerts.ps1
  Cloudmarque.Azure/Resources/Project/Integration/logAlerts.yml
  Cloudmarque.Azure/Resources/Project/Integration/metricAlerts.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzMonitorLogAlerts.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzMonitorMetricAlerts.Schema.json
Labels: enhancement

#298 Fix schedule logic and default values.
  Cloudmarque.Azure/Public/Deploy/Monitor/logAlerts/New-CmAzMonitorLogAlerts.ps1
  Cloudmarque.Azure/Public/Deploy/Monitor/logAlerts/standardDefinitions.yml
  Cloudmarque.Azure/Resources/Project/Integration/logAlerts.yml
  Cloudmarque.Azure/Resources/Project/Integration/metricAlerts.yml
Labels: enhancement

#300 update release notes
  Cloudmarque.Azure/Cloudmarque.Azure.psd1
Labels: enhancement

#302 Unit test fixes
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/privateEndpoints/New-CmAzIaasPrivateEndpoints.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/storage/New-CmAzIaasStorage.ps1
  Cloudmarque.Azure/Public/Deploy/Monitor/logAlerts/New-CmAzMonitorLogAlerts.ps1
  Cloudmarque.Azure/Public/Deploy/Monitor/metricAlerts/New-CmAzMonitorMetricAlerts.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction.ps1
  Cloudmarque.Azure/Public/New-CmAzDeployment.ps1
  Cloudmarque.Azure/Resources/Project/Integration/functions.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzPaasWeb.Schema.json
  azure-pipelines.yml
Labels: bug

#301 Move security stage
  azure-integration-pipelines.yml
Labels: enhancement

#304 Pipeline fix test publish
  azure-pipelines.yml
Labels: bug

#311 remove uneeded file
  Cloudmarque.Azure/Resources/Project/Integration/naming.yaml
Labels: bug

#313 Fix Automation Schema Spacing for Jekyll Build
  Cloudmarque.Azure/Resources/Schema/New-CmAzCoreAutomation.Schema.json
Labels: bug

#315 Fix schemas for doc build
  Cloudmarque.Azure/Resources/Schema/New-CmAzCoreKeyVault.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasRecoveryServicesVault.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzIaasStorage.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzPaasFunction.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzPaasSql.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzPaasWeb.Schema.json
Labels: bug

#310 Change region to location
  Cloudmarque.Azure/Public/Common/Get-CmAzResourceName.ps1
  Cloudmarque.Azure/Public/Common/Get-CmAzService.ps1
  Cloudmarque.Azure/Public/Deploy/Core/automation/New-CmAzCoreAutomation.ps1
  Cloudmarque.Azure/Public/Deploy/Core/automation/Set-CmAzCoreAutomationDeleteResource.ps1
  Cloudmarque.Azure/Public/Deploy/Core/budgets/New-CmAzCoreBillingRule.ps1
  Cloudmarque.Azure/Public/Deploy/Core/keyvault/New-CmAzCoreKeyVault.ps1
  Cloudmarque.Azure/Public/Deploy/Core/monitoring/New-CmAzCoreMonitor.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/bastionhost/New-CmAzIaasBastionHost.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/managedNetwork/New-CmAzIaasNetworking.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/privateEndpoints/New-CmAzIaasPrivateEndpoints.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/networking/vnetPeerings/New-CmAzIaasVnetPeerings.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/recoveryvault/New-CmAzIaasRecoveryServicesVault.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/storage/New-CmAzIaasStorage.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/New-CmAzIaasVm.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/vm/Set-CmAzIaasUpdateManagement.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/vpngw/New-CmAzIaasVpnGw.ps1
  Cloudmarque.Azure/Public/Deploy/IaaS/wvd/New-CmAzIaasWvd.ps1
  Cloudmarque.Azure/Public/Deploy/Monitor/logAlerts/New-CmAzMonitorLogAlerts.ps1
  Cloudmarque.Azure/Public/Deploy/Monitor/metricAlerts/New-CmAzMonitorMetricAlerts.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/function/New-CmAzPaasFunction.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.json
  Cloudmarque.Azure/Public/Deploy/PaaS/sharedImageGallery/New-CmAzPaasSharedImageGallery.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/sql/New-CmAzPaasSql.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/web-static/New-CmAzPaasWebStatic.ps1
  Cloudmarque.Azure/Public/Deploy/PaaS/web/New-CmAzPaasWeb.ps1
  Cloudmarque.Azure/Public/Deploy/Security/security-centre/Set-CmAzSecurityCentre.ps1
  Cloudmarque.Azure/Resources/Project/Integration/_names/generators.yml
  Cloudmarque.Azure/Resources/Project/Integration/_names/locations.yml
  Cloudmarque.Azure/Resources/Project/Integration/monitor.yml
  Cloudmarque.Azure/Resources/Project/Integration/sharedImageGallery.yml
  Cloudmarque.Azure/Resources/Project/Integration/virtualmachines.yml
  Cloudmarque.Azure/Resources/Project/Integration/web.yml
  Cloudmarque.Azure/Resources/Schema/New-CmAzCoreMonitor.Schema.json
  Cloudmarque.Azure/Resources/Schema/New-CmAzPaasSharedImageGallery.Schema.json
  Tests/Get-CmAzResourceName.Tests.ps1
  azure-integration-pipelines.yml
Labels: consistency
